export const DSA_ROADMAP = [
  {
    id: "arrays",
    title: "Arrays",
    description: "Fundamental data structure for storing collections of items.",
    icon: "ArrayIcon",
    prerequisites: [],
  },
  {
    id: "strings",
    title: "Strings",
    description: "Sequence of characters, often involving manipulation and searching.",
    icon: "TypeIcon",
    prerequisites: ["arrays"],
  },
  {
    id: "hashing",
    title: "Hashing",
    description: "Using hash tables for O(1) lookups and frequency counting.",
    icon: "HashIcon",
    prerequisites: ["arrays", "strings"],
  },
  {
    id: "two-pointers",
    title: "Two Pointers",
    description: "Iterating with two pointers to solve array/string problems efficiently.",
    icon: "FastForwardIcon",
    prerequisites: ["arrays", "strings"],
  },
  {
    id: "sliding-window",
    title: "Sliding Window",
    description: "Maintaining a window that satisfies certain conditions.",
    icon: "MaximizeIcon",
    prerequisites: ["arrays", "strings", "two-pointers"],
  },
  {
    id: "binary-search",
    title: "Binary Search",
    description: "O(log n) search on sorted data or monotonic functions.",
    icon: "SearchIcon",
    prerequisites: ["arrays"],
  },
  {
    id: "sorting",
    title: "Sorting",
    description: "Organizing data in a specific order.",
    icon: "SortAscIcon",
    prerequisites: ["arrays"],
  },
  {
    id: "linked-list",
    title: "Linked List",
    description: "Sequential data structure with nodes pointing to each other.",
    icon: "LinkIcon",
    prerequisites: [],
  },
  {
    id: "stack",
    title: "Stack",
    description: "LIFO data structure.",
    icon: "LayersIcon",
    prerequisites: ["arrays", "linked-list"],
  },
  {
    id: "queue",
    title: "Queue",
    description: "FIFO data structure.",
    icon: "ListIcon",
    prerequisites: ["arrays", "linked-list"],
  },
  {
    id: "trees",
    title: "Trees",
    description: "Hierarchical data structure.",
    icon: "NetworkIcon",
    prerequisites: ["stack", "queue"],
  },
  {
    id: "bst",
    title: "Binary Search Tree",
    description: "Tree with sorted properties for fast lookup/insertion.",
    icon: "BinaryIcon",
    prerequisites: ["trees", "binary-search"],
  },
  {
    id: "heap",
    title: "Heap / Priority Queue",
    description: "Tree-based structure for efficiently finding min/max.",
    icon: "TrendingUpIcon",
    prerequisites: ["trees"],
  },
  {
    id: "graphs",
    title: "Graphs",
    description: "Nodes and edges representing relationships.",
    icon: "Share2Icon",
    prerequisites: ["trees", "stack", "queue"],
  },
  {
    id: "greedy",
    title: "Greedy",
    description: "Making locally optimal choices to find a global optimum.",
    icon: "ZapIcon",
    prerequisites: ["sorting", "heap"],
  },
  {
    id: "backtracking",
    title: "Backtracking",
    description: "Exploring all paths and abandoning invalid ones.",
    icon: "CornerUpLeftIcon",
    prerequisites: ["trees", "recursion"],
  },
  {
    id: "dynamic-programming",
    title: "Dynamic Programming",
    description: "Solving overlapping subproblems and remembering solutions.",
    icon: "CpuIcon",
    prerequisites: ["backtracking"],
  },
  {
    id: "bit-manipulation",
    title: "Bit Manipulation",
    description: "Operating directly on binary representations.",
    icon: "HashIcon",
    prerequisites: ["arrays", "math"],
  }
];
